package com.gmail.volkovskiyda.abit.buildlogic

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Writes the git-derived version name into a Kotlin constant, so shared code can show which build
 * the user is running.
 *
 * It is generated rather than typed because [AbitVersioning] derives the number from `-PbuildNumber`
 * and `-PbaseVersion` at configuration time and nothing in this repository is edited per release —
 * a committed constant would be wrong on every build but one. Android has `BuildConfig` for exactly
 * this, but `app:shared` is multiplatform: desktop and web have no `BuildConfig`, and four copies of
 * the number read out of four places is how they drift apart.
 */
abstract class GenerateAppVersionTask : DefaultTask() {
    /** The version name to bake in — always [AbitVersioning.versionName]. */
    @get:Input
    abstract val versionName: Property<String>

    /** The package the constant is declared in, so the consuming module can keep it `internal`. */
    @get:Input
    abstract val packageName: Property<String>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val root = outputDirectory.get().asFile
        // Stale output would otherwise survive a package rename and compile alongside the new file.
        root.deleteRecursively()
        val packagePath = packageName.get().replace('.', '/')
        val target = root.resolve(packagePath).apply { mkdirs() }.resolve("AbitBuild.kt")
        target.writeText(
            """
            |// Generated by the abit.appversion convention plugin. Do not edit.
            |package ${packageName.get()}
            |
            |/** The running build's version name — `<tag>.<commit count>`, or `1.0` built locally. */
            |internal const val ABIT_VERSION_NAME: String = "${versionName.get()}"
            |
            """.trimMargin(),
        )
    }
}
